name: Build and Deploy Script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}
          angular_project_dir: ./
          build_configuration: production
          angular_dist_build_folder: /docs
